spring:
  mvc:
    static-path-pattern: "/**"
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: "50MB"
      max-request-size: "50MB"

  datasource:
    url: jdbc:mysql://47.108.55.234:3306/mall
    username: root
    password: '!Zq284067'
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.springboot.zq.*
      filters: stat,wall
#     监控页
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
#     网页访问监控
      web-stat-filter:
        enabled: true
        url-pattern: /*

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
#          配置防火墙属性，例如 禁止插入
#          config:
#            insert-allow: false
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: true
    default-property-inclusion: non_null


mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
#    驼峰体映射
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true


